# Generated by Django 3.2.9 on 2021-11-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='day',
            field=models.CharField(blank=True, choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=280),
        ),
    ]
