# Generated by Django 3.2.9 on 2021-12-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0002_auto_20211130_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='sentiment',
            new_name='Suggested_Sentiment',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='day',
            field=models.CharField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='hour',
            field=models.IntegerField(),
        ),
    ]
